backend:
  name: git-gateway
  repo: nterol/recipes_website

media_folder: static/assets
public_folder: /assets

collections: 
  - name: Popotes de potes
    label: popotes de potes
    folder: blog
    create: true
    fields: 
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
